//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by RemoteCtrl.rc
//
#define IDD_DIALOG_HOST_MAIN             101
#define IDD_DIALOG_CONSENT               102
#define IDS_APP_TITLE                    103

#define IDC_STATIC_HOST_IP_LABEL         1000
#define IDC_STATIC_HOST_IP_VALUE         1001
#define IDC_STATIC_HOST_PORT_LABEL       1002
#define IDC_STATIC_HOST_PORT_VALUE       1003
#define IDC_STATIC_SESSION_CODE_LABEL    1004
#define IDC_STATIC_SESSION_CODE_VALUE    1005
#define IDC_STATIC_STATUS_LABEL          1006
#define IDC_STATIC_STATUS_VALUE          1007
#define IDC_BTN_STOP_SHARING             1008
#define IDC_STATIC_CONSENT_MESSAGE       1009
#define IDC_STATIC_CONSENT_VIEWER_IP_LABEL 1010
#define IDC_STATIC_CONSENT_VIEWER_IP_VALUE 1011
#define IDC_STATIC_CONSENT_HELPER_NAME_LABEL 1012
#define IDC_STATIC_CONSENT_HELPER_NAME_VALUE 1013
#define IDC_STATIC_CONSENT_SESSION_CODE_LABEL 1014
#define IDC_STATIC_CONSENT_SESSION_CODE_VALUE 1015
#define IDC_STATIC_CONSENT_HOST_NAME_LABEL 1016
#define IDC_STATIC_CONSENT_HOST_NAME_VALUE 1017
#define IDC_STATIC_CONSENT_COUNTDOWN     1018

#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE         104
#define _APS_NEXT_COMMAND_VALUE          40004
#define _APS_NEXT_CONTROL_VALUE          1019
#define _APS_NEXT_SYMED_VALUE            101
#endif
#endif
